---
all:
  children:
    givegrove_dev:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: "{{ ansible_env.USER | default('developer') }}"
        vm_instance:
          ansible_host: 174.138.71.207
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_digital_ocean
      vars:
        # Repository configuration
        repo_url: "https://github.com/south-bend-code-works/GiveGrove.git"
        repo_branch: "beta"
        
        # Software versions (matching CLAUDE.md requirements)
        node_version: "20.17.0"
        npm_version: "10.6.0"
        firebase_cli_version: "13.27.0"
        
        # Development environment
        enable_gui: true
        enable_vnc: true
        vnc_port: 5900
        virtual_display: ":99"
        
        # Paths
        home_dir: "/home/{{ ansible_user }}"
        repo_dir: "{{ home_dir }}/GiveGrove"
        secrets_dir: "{{ repo_dir }}/secrets"