---
# Test Git and Firebase Authentication
- name: Test Authentication Setup
  hosts: vm_instance
  become: yes
  vars_files:
    - secrets.yml
  vars:
    workspace_dir: "/root/GiveGrove"
    
  tasks:
    # Git Authentication Test
    - name: Configure Git with authentication
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { name: "user.name", value: "Joshua Mullet" }
        - { name: "user.email", value: "joshua.mullet@gmail.com" }
        - { name: "credential.helper", value: "store" }

    - name: Create Git credentials file
      copy:
        content: "https://{{ vault_github_username }}:{{ vault_github_token }}@github.com"
        dest: "/root/.git-credentials"
        mode: '0600'

    # Firebase Authentication Test
    - name: Create Firebase service account key
      copy:
        content: "{{ vault_firebase_service_account_json }}"
        dest: "/root/.firebase-service-account.json"
        mode: '0600'

    - name: Set Firebase authentication environment
      lineinfile:
        path: /root/.bashrc
        line: 'export GOOGLE_APPLICATION_CREDENTIALS="/root/.firebase-service-account.json"'
        create: yes

    # Test Git Authentication
    - name: Test git clone with authentication
      git:
        repo: "https://{{ vault_github_username }}:{{ vault_github_token }}@github.com/south-bend-code-works/GiveGrove.git"
        dest: "{{ workspace_dir }}-test"
        force: yes

    # Test Firebase Authentication
    - name: Test Firebase authentication
      shell: |
        export GOOGLE_APPLICATION_CREDENTIALS="/root/.firebase-service-account.json"
        firebase --version
        firebase projects:list
      register: firebase_test

    - name: Display Firebase test results
      debug:
        msg: "{{ firebase_test.stdout }}"

    - name: Display success message
      debug:
        msg: |
          🎉 Authentication Test Complete!
          
          ✅ Git: Successfully cloned repository
          ✅ Firebase: Service account authentication working
          
          Both authentication methods are ready for full automation!